# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            JoshWood
tagline:          'I want to believe...'
description:      'Those expecting logic or consistency from the world are doomed to be disappointed.'
url:              http://joshwood.github.io
baseurl:          /

author:
  name:           'JoshWood'
  url:            http://joshwood.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/joshwood

plunker:
  repo:           http://plnkr.co/users/joshwood